--- #YAML:1.0
name:                Test-UseAllModules
version:             0.09_01
abstract:            do use_ok() for all the MANIFESTed modules
license:             perl
author:              
    - Kenichi Ishigaki <ishigaki@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Exporter:                      0
    ExtUtils::Manifest:            0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
